In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('employment.txt', sep=",")
state_code = pd.read_csv('statecode.txt', sep='\t')
industry_code = pd.read_csv('Industrycode.txt', sep ='\t')

In [3]:
print(len(data))
print(state_code)
print(industry_code)

1727
    code                  name
0      1               Alabama
1      2                Alaska
2      4               Arizona
3      5              Arkansas
4      6            California
5      8              Colorado
6      9           Connecticut
7     10              Delaware
8     11  District of Columbia
9     12               Florida
10    13               Georgia
11    15                Hawaii
12    16                 Idaho
13    17              Illinois
14    18               Indiana
15    19                  Iowa
16    20                Kansas
17    21              Kentucky
18    22             Louisiana
19    23                 Maine
20    24              Maryland
21    25         Massachusetts
22    26              Michigan
23    27             Minnesota
24    28           Mississippi
25    29              Missouri
26    30               Montana
27    31              Nebraska
28    32                Nevada
29    33         New Hampshire
30    34            New Jersey
31    35            New Mexico
32    36              New York
33    37        North Carolina
34    38          North Dakota
35    39                  Ohio
36    40              Oklahoma
37    41                Oregon
38    42          Pennsylvania
39    44          Rhode Island
40    45        South Carolina
41    46          South Dakota
42    47             Tennessee
43    48                 Texas
44    49                  Utah
45    50               Vermont
46    51              Virginia
47    53            Washington
48    54         West Virginia
49    55             Wisconsin
50    56               Wyoming
51    72           Puerto Rico
52    78        Virgin Islands
        code                                          name
0          0                                 Total Nonfarm
1    5000000                                 Total Private
2    6000000                               Goods Producing
3    7000000                             Service-Providing
4    8000000                     Private Service Providing
5   10000000                               Mining, Logging
6   15000000                 Mining, Logging, Construction
7   20000000                                  Construction
8   30000000                                 Manufacturing
9   31000000                                 Durable Goods
10  32000000                             Non-Durable Goods
11  40000000              Trade, Transportation, Utilities
12  41000000                               Wholesale Trade
13  42000000                                  Retail Trade
14  43000000        Transportation, Warehousing, Utilities
15  50000000                                   Information
16  55000000                          Financial Activities
17  55520000                         Finance and Insurance
18  55530000                  Real Estate, Rental, Leasing
19  60000000            Professional and Business Services
20  60540000  Professional, Scientific, Technical Services
21  60550000       Management if Companies and Enterprises
22  60560000                           Ad-Sp-WM-R Services
23  65000000                    Education, Health Services
24  65610000                          Educational Services
25  65620000                Health Care, Social Assistance
26  70000000                       Leisure and Hospitality
27  70710000               Arts, Entertainment, Recreation
28  70720000               Accommodation and Food Services
29  80000000                                Other Services
30  90000000                                    Government
31  90910000                            Federal Government
32  90920000                              State Government
33  90930000                              Local Government

In [4]:
data.head()

,Series ID,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,...,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019,Sep 2019,Oct 2019,Nov 2019,Dec 2019
0,SMS01000000000000001,1921.1,1927.2,1929.9,1928.8,1930.2,1933.9,1935.9,1935.7,1939.7,...,2069.0,2070.0,2074.9,2078.4,2084.5,2087.5,2090.6,,,
1,SMS01000000500000001,1569.0,1574.4,1576.3,1574.0,1576.8,1580.2,1581.1,1581.2,1584.7,...,1683.6,1682.9,1685.2,1690.9,1696.3,1698.7,1701.9,,,
2,SMS01000000600000001,478.4,477.8,476.5,478.7,479.1,477.7,477.1,475.5,475.2,...,374.2,373.9,373.6,374.4,373.7,374.4,375.4,,,
3,SMS01000000700000001,1442.7,1449.4,1453.4,1450.1,1451.1,1456.2,1458.8,1460.2,1464.5,...,1694.8,1696.1,1701.3,1704.0,1710.8,1713.1,1715.2,,,
4,SMS01000000800000001,1090.6,1096.6,1099.8,1095.3,1097.7,1102.5,1104.0,1105.7,1109.5,...,1309.4,1309.0,1311.6,1316.5,1322.6,1324.3,1326.5,,,

In [5]:
series_id = data['Series ID']
states_data = []
industry_data = []

state_data = []
industry_data = []

for index, row in data.iterrows():
    state_data.append(state_code[state_code['code'] == int(row['Series ID'][3:5])]['name'].iloc[0])
    industry_data.append(industry_code[industry_code['code'] == int(row['Series ID'][10:18])]['name'].iloc[0])
data['state'] = state_data
data['industry'] = industry_data
# print (industry_data)

In [6]:
data.head()

,Series ID,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,...,May 2019,Jun 2019,Jul 2019,Aug 2019,Sep 2019,Oct 2019,Nov 2019,Dec 2019,state,industry
0,SMS01000000000000001,1921.1,1927.2,1929.9,1928.8,1930.2,1933.9,1935.9,1935.7,1939.7,...,2074.9,2078.4,2084.5,2087.5,2090.6,,,,Alabama,Total Nonfarm
1,SMS01000000500000001,1569.0,1574.4,1576.3,1574.0,1576.8,1580.2,1581.1,1581.2,1584.7,...,1685.2,1690.9,1696.3,1698.7,1701.9,,,,Alabama,Total Private
2,SMS01000000600000001,478.4,477.8,476.5,478.7,479.1,477.7,477.1,475.5,475.2,...,373.6,374.4,373.7,374.4,375.4,,,,Alabama,Goods Producing
3,SMS01000000700000001,1442.7,1449.4,1453.4,1450.1,1451.1,1456.2,1458.8,1460.2,1464.5,...,1701.3,1704.0,1710.8,1713.1,1715.2,,,,Alabama,Service-Providing
4,SMS01000000800000001,1090.6,1096.6,1099.8,1095.3,1097.7,1102.5,1104.0,1105.7,1109.5,...,1311.6,1316.5,1322.6,1324.3,1326.5,,,,Alabama,Private Service Providing

In [7]:
data.head(50)

,Series ID,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,...,May 2019,Jun 2019,Jul 2019,Aug 2019,Sep 2019,Oct 2019,Nov 2019,Dec 2019,state,industry
0,SMS01000000000000001,1921.1,1927.2,1929.9,1928.8,1930.2,1933.9,1935.9,1935.7,1939.7,...,2074.9,2078.4,2084.5,2087.5,2090.6,,,,Alabama,Total Nonfarm
1,SMS01000000500000001,1569.0,1574.4,1576.3,1574.0,1576.8,1580.2,1581.1,1581.2,1584.7,...,1685.2,1690.9,1696.3,1698.7,1701.9,,,,Alabama,Total Private
2,SMS01000000600000001,478.4,477.8,476.5,478.7,479.1,477.7,477.1,475.5,475.2,...,373.6,374.4,373.7,374.4,375.4,,,,Alabama,Goods Producing
3,SMS01000000700000001,1442.7,1449.4,1453.4,1450.1,1451.1,1456.2,1458.8,1460.2,1464.5,...,1701.3,1704.0,1710.8,1713.1,1715.2,,,,Alabama,Service-Providing
4,SMS01000000800000001,1090.6,1096.6,1099.8,1095.3,1097.7,1102.5,1104.0,1105.7,1109.5,...,1311.6,1316.5,1322.6,1324.3,1326.5,,,,Alabama,Private Service Providing
5,SMS01000001000000001,16.3,16.4,16.2,15.4,15.4,15.4,15.2,15.1,15.1,...,9.9,9.9,9.9,9.9,9.9,,,,Alabama,"Mining, Logging"
6,SMS01000001500000001,119.0,119.8,119.8,118.3,118.5,118.3,118.8,118.7,119.2,...,104.5,104.9,104.5,104.1,104.5,,,,Alabama,"Mining, Logging, Construction"
7,SMS01000002000000001,102.7,103.4,103.6,102.9,103.1,102.9,103.6,103.6,104.1,...,94.6,95.0,94.6,94.2,94.6,,,,Alabama,Construction
8,SMS01000003000000001,359.4,358.0,356.7,360.4,360.6,359.4,358.3,356.8,356.0,...,269.1,269.5,269.2,270.3,270.9,,,,Alabama,Manufacturing
9,SMS01000003100000001,189.9,189.5,189.0,189.7,190.3,190.5,190.4,190.6,190.6,...,176.5,177.2,177.7,178.3,179.1,,,,Alabama,Durable Goods
10,SMS01000003200000001,169.5,168.5,167.7,170.7,170.3,168.9,167.9,166.2,165.4,...,92.6,92.3,91.5,92.0,91.8,,,,Alabama,Non-Durable Goods
11,SMS01000004000000001,379.9,382.5,384.4,381.4,382.5,383.9,384.4,385.1,386.3,...,382.9,383.8,384.5,386.4,385.1,,,,Alabama,"Trade, Transportation, Utilities"
12,SMS01000004100000001,82.0,82.1,82.4,82.1,82.2,82.3,82.5,82.5,82.9,...,73.8,73.8,73.5,74.0,74.2,,,,Alabama,Wholesale Trade
13,SMS01000004200000001,229.9,232.1,233.6,230.6,231.9,233.5,233.8,234.7,235.6,...,231.6,231.5,232.9,234.4,233.3,,,,Alabama,Retail Trade
14,SMS01000004300000001,68.0,68.3,68.4,68.7,68.4,68.1,68.1,67.9,67.8,...,77.5,78.5,78.1,78.0,77.6,,,,Alabama,"Transportation, Warehousing, Utilities"
15,SMS01000005000000001,31.6,31.7,31.8,31.9,32.2,32.3,32.4,32.6,32.5,...,21.5,21.7,21.6,21.5,21.3,,,,Alabama,Information
16,SMS01000005500000001,96.8,97.4,97.5,97.2,97.5,97.6,97.4,97.5,97.7,...,97.7,98.4,98.3,97.6,97.8,,,,Alabama,Financial Activities
17,SMS01000005552000001,73.9,74.2,74.6,74.4,74.6,74.6,74.4,74.3,74.4,...,73.8,74.2,74.2,73.8,74.8,,,,Alabama,Finance and Insurance
18,SMS01000005553000001,22.9,23.2,22.9,22.8,22.9,23.0,23.0,23.2,23.3,...,23.9,24.2,24.1,23.8,23.0,,,,Alabama,"Real Estate, Rental, Leasing"
19,SMS01000006000000001,177.7,178.6,178.9,179.0,180.0,180.5,180.3,180.4,181.4,...,251.5,253.3,254.0,254.4,254.9,,,,Alabama,Professional and Business Services
20,SMS01000006054000001,75.4,75.7,75.7,75.7,76.1,76.2,76.4,76.6,77.2,...,108.7,109.3,108.9,107.6,107.3,,,,Alabama,"Professional, Scientific, Technical Services"
21,SMS01000006055000001,12.4,12.4,12.4,12.1,12.1,12.1,12.1,12.1,12.1,...,15.9,16.0,16.0,15.8,15.8,,,,Alabama,Management if Companies and Enterprises
22,SMS01000006056000001,89.9,90.5,90.8,91.2,91.8,92.2,91.8,91.7,92.1,...,126.9,128.0,129.1,131.0,131.8,,,,Alabama,Ad-Sp-WM-R Services
23,SMS01000006500000001,176.3,176.8,176.9,177.2,177.0,178.1,177.6,177.2,178.1,...,248.1,249.3,252.0,252.0,251.8,,,,Alabama,"Education, Health Services"
24,SMS01000006561000001,27.4,27.8,27.7,28.4,28.1,28.7,28.4,28.3,28.8,...,30.5,30.8,31.5,30.9,30.8,,,,Alabama,Educational Services
25,SMS01000006562000001,148.9,149.0,149.2,148.8,148.9,149.4,149.2,148.9,149.3,...,217.6,218.5,220.5,221.1,221.0,,,,Alabama,"Health Care, Social Assistance"
26,SMS01000007000000001,148.3,149.3,149.6,147.7,147.3,148.3,149.6,149.9,150.1,...,211.4,210.9,212.3,212.8,215.5,,,,Alabama,Leisure and Hospitality
27,SMS01000007071000001,14.6,14.7,14.7,15.2,15.0,15.2,15.2,15.1,15.2,...,21.3,20.7,20.1,20.4,21.7,,,,Alabama,"Arts, Entertainment, Recreation"
28,SMS01000007072000001,133.7,134.6,134.9,132.5,132.3,133.1,134.4,134.8,134.9,...,190.1,190.2,192.2,192.4,193.8,,,,Alabama,Accommodation and Food Services
29,SMS01000008000000001,80.0,80.3,80.7,80.9,81.2,81.8,82.3,83.0,83.4,...,98.5,99.1,99.9,99.6,100.1,,,,Alabama,Other Services
30,SMS01000009000000001,352.1,352.8,353.6,354.8,353.4,353.7,354.8,354.5,355.0,...,389.7,387.5,388.2,388.8,388.7,,,,Alabama,Government
31,SMS01000009091000001,53.7,53.7,54.0,53.8,53.0,52.9,52.8,52.8,52.9,...,53.6,53.6,53.5,54.1,54.2,,,,Alabama,Federal Government
32,SMS01000009092000001,98.9,98.8,99.0,99.6,99.0,99.1,99.2,99.4,100.0,...,118.6,115.7,116.2,116.1,115.8,,,,Alabama,State Government
33,SMS01000009093000001,199.5,200.3,200.6,201.4,201.4,201.7,202.8,202.3,202.1,...,217.5,218.2,218.5,218.6,218.7,,,,Alabama,Local Government
34,SMS02000000000000001,278.6,277.1,278.6,278.4,278.2,277.9,278.0,278.4,280.4,...,332.3,332.5,331.5,330.7,331.1,,,,Alaska,Total Nonfarm
35,SMS02000000500000001,205.6,204.1,205.4,204.8,204.7,204.9,204.6,205.4,207.2,...,252.0,252.0,250.8,250.0,250.6,,,,Alaska,Total Private
36,SMS02000000600000001,39.9,38.1,38.7,38.2,37.8,36.8,37.0,37.1,37.7,...,43.2,44.3,44.0,44.2,44.7,,,,Alaska,Goods Producing
37,SMS02000000700000001,238.7,239.0,239.9,240.2,240.4,241.1,241.0,241.3,242.7,...,289.1,288.2,287.5,286.5,286.4,,,,Alaska,Service-Providing
38,SMS02000000800000001,165.7,166.0,166.7,166.6,166.9,168.1,167.6,168.3,169.5,...,208.8,207.7,206.8,205.8,205.9,,,,Alaska,Private Service Providing
39,SMS02000001000000001,11.3,11.1,11.0,10.7,10.6,10.5,10.2,10.0,10.2,...,13.5,13.6,13.7,13.8,13.9,,,,Alaska,"Mining, Logging"
40,SMS02000001500000001,25.7,24.8,25.0,25.1,24.6,24.3,24.3,24.2,24.6,...,30.7,30.6,30.4,30.7,30.9,,,,Alaska,"Mining, Logging, Construction"
41,SMS02000002000000001,14.4,13.7,14.0,14.4,14.0,13.8,14.1,14.2,14.4,...,17.2,17.0,16.7,16.9,17.0,,,,Alaska,Construction
42,SMS02000003000000001,14.2,13.3,13.7,13.1,13.2,12.5,12.7,12.9,13.1,...,12.5,13.7,13.6,13.5,13.8,,,,Alaska,Manufacturing
43,SMS02000003100000001,2.1,1.8,2.1,2.1,2.0,2.0,2.0,1.7,1.6,...,1.8,1.8,1.9,1.9,1.7,,,,Alaska,Durable Goods
44,SMS02000003200000001,12.1,11.5,11.6,11.0,11.2,10.5,10.7,11.2,11.5,...,10.7,11.9,11.7,11.6,12.1,,,,Alaska,Non-Durable Goods
45,SMS02000004000000001,59.3,59.7,59.7,59.7,59.5,60.1,59.9,60.0,60.4,...,64.9,64.4,64.7,64.5,65.0,,,,Alaska,"Trade, Transportation, Utilities"
46,SMS02000004100000001,6.2,6.3,6.2,6.3,6.2,6.3,6.3,6.3,6.4,...,6.5,6.5,6.5,6.6,6.7,,,,Alaska,Wholesale Trade
47,SMS02000004200000001,33.2,33.4,33.5,33.4,33.1,33.6,33.7,33.8,34.1,...,36.0,35.6,36.0,35.6,36.2,,,,Alaska,Retail Trade
48,SMS02000004300000001,19.9,20.0,20.0,20.0,20.2,20.2,19.9,19.9,19.9,...,22.4,22.3,22.2,22.3,22.1,,,,Alaska,"Transportation, Warehousing, Utilities"
49,SMS02000005000000001,6.4,6.4,6.5,6.4,6.9,6.8,7.0,7.1,7.2,...,5.5,5.6,5.6,5.6,5.5,,,,Alaska,Information

In [8]:
def filter_data(data):    
    missing_var_in_state = {}
    all_var = np.array(industry_code['name'])
    for index, row in state_code['name'].iteritems():
        print (row)
        state_data = data[data['state'] == row]
        num_of_variables = len(state_data)
        print (num_of_variables)
        state_var = np.array(state_data['industry'])
        empty_var = [var for var in all_var if var not in state_var]
        missing_var_in_state[row] = {'number_of_missing': len(empty_var), 'missing_vars': empty_var}
        print ("Empty variables", empty_var)
        print ()

    missing_state_in_var = {}
    all_state = np.array(state_code['name'])
    for index, row in industry_code['name'].iteritems():
        print (row)
        state_data = data[data['industry'] == row]
        num_of_states = len(state_data)
        print (num_of_states)
        var_state = np.array(state_data['state'])
        empty_state = [state for state in all_state if state not in var_state]
        missing_state_in_var[row] = {'number_of_missing': len(empty_state), 'missing_states': empty_state}
        print ("Empty state", empty_state)
        print ()
    return missing_state_in_var, missing_var_in_state

In [9]:

missing_state_in_var, missing_var_in_state = filter_data(data)

print(missing_var_in_state)
print(missing_state_in_var)

Alabama
34
Empty variables []

Alaska
31
Empty variables ['Finance and Insurance', 'Educational Services', 'Health Care, Social Assistance']

Arizona
33
Empty variables ['Non-Durable Goods']

Arkansas
34
Empty variables []

California
34
Empty variables []

Colorado
34
Empty variables []

Connecticut
34
Empty variables []

Delaware
31
Empty variables ['Mining, Logging', 'Construction', 'Information']

District of Columbia
27
Empty variables ['Mining, Logging', 'Construction', 'Durable Goods', 'Non-Durable Goods', 'Management if Companies and Enterprises', 'State Government', 'Local Government']

Florida
33
Empty variables ['Mining, Logging']

Georgia
34
Empty variables []

Hawaii
32
Empty variables ['Mining, Logging', 'Construction']

Idaho
34
Empty variables []

Illinois
34
Empty variables []

Indiana
34
Empty variables []

Iowa
34
Empty variables []

Kansas
34
Empty variables []

Kentucky
34
Empty variables []

Louisiana
33
Empty variables ['Finance and Insurance']

Maine
34
Empty variables []

Maryland
34
Empty variables []

Massachusetts
34
Empty variables []

Michigan
34
Empty variables []

Minnesota
34
Empty variables []

Mississippi
34
Empty variables []

Missouri
33
Empty variables ['Finance and Insurance']

Montana
31
Empty variables ['Finance and Insurance', 'Management if Companies and Enterprises', 'Educational Services']

Nebraska
34
Empty variables []

Nevada
34
Empty variables []

New Hampshire
34
Empty variables []

New Jersey
34
Empty variables []

New Mexico
23
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Health Care, Social Assistance', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

New York
34
Empty variables []

North Carolina
34
Empty variables []

North Dakota
33
Empty variables ['Management if Companies and Enterprises']

Ohio
34
Empty variables []

Oklahoma
31
Empty variables ['Durable Goods', 'Information', 'Finance and Insurance']

Oregon
34
Empty variables []

Pennsylvania
34
Empty variables []

Rhode Island
32
Empty variables ['Information', 'Real Estate, Rental, Leasing']

South Carolina
34
Empty variables []

South Dakota
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Tennessee
34
Empty variables []

Texas
34
Empty variables []

Utah
34
Empty variables []

Vermont
33
Empty variables ['Management if Companies and Enterprises']

Virginia
34
Empty variables []

Washington
34
Empty variables []

West Virginia
33
Empty variables ['Management if Companies and Enterprises']

Wisconsin
34
Empty variables []

Wyoming
32
Empty variables ['Finance and Insurance', 'Management if Companies and Enterprises']

Puerto Rico
32
Empty variables ['Management if Companies and Enterprises', 'Arts, Entertainment, Recreation']

Virgin Islands
13
Empty variables ['Mining, Logging', 'Mining, Logging, Construction', 'Construction', 'Manufacturing', 'Durable Goods', 'Non-Durable Goods', 'Wholesale Trade', 'Information', 'Financial Activities', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional and Business Services', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Health Care, Social Assistance', 'Arts, Entertainment, Recreation', 'Other Services', 'Federal Government', 'Local Government']

Total Nonfarm
53
Empty state []

Total Private
53
Empty state []

Goods Producing
53
Empty state []

Service-Providing
53
Empty state []

Private Service Providing
53
Empty state []

Mining, Logging
48
Empty state ['Delaware', 'District of Columbia', 'Florida', 'Hawaii', 'Virgin Islands']

Mining, Logging, Construction
52
Empty state ['Virgin Islands']

Construction
49
Empty state ['Delaware', 'District of Columbia', 'Hawaii', 'Virgin Islands']

Manufacturing
52
Empty state ['Virgin Islands']

Durable Goods
48
Empty state ['District of Columbia', 'New Mexico', 'Oklahoma', 'South Dakota', 'Virgin Islands']

Non-Durable Goods
48
Empty state ['Arizona', 'District of Columbia', 'New Mexico', 'South Dakota', 'Virgin Islands']

Trade, Transportation, Utilities
53
Empty state []

Wholesale Trade
52
Empty state ['Virgin Islands']

Retail Trade
53
Empty state []

Transportation, Warehousing, Utilities
53
Empty state []

Information
49
Empty state ['Delaware', 'Oklahoma', 'Rhode Island', 'Virgin Islands']

Financial Activities
52
Empty state ['Virgin Islands']

Finance and Insurance
44
Empty state ['Alaska', 'Louisiana', 'Missouri', 'Montana', 'New Mexico', 'Oklahoma', 'South Dakota', 'Wyoming', 'Virgin Islands']

Real Estate, Rental, Leasing
49
Empty state ['New Mexico', 'Rhode Island', 'South Dakota', 'Virgin Islands']

Professional and Business Services
52
Empty state ['Virgin Islands']

Professional, Scientific, Technical Services
50
Empty state ['New Mexico', 'South Dakota', 'Virgin Islands']

Management if Companies and Enterprises
43
Empty state ['District of Columbia', 'Montana', 'New Mexico', 'North Dakota', 'South Dakota', 'Vermont', 'West Virginia', 'Wyoming', 'Puerto Rico', 'Virgin Islands']

Ad-Sp-WM-R Services
50
Empty state ['New Mexico', 'South Dakota', 'Virgin Islands']

Education, Health Services
53
Empty state []

Educational Services
49
Empty state ['Alaska', 'Montana', 'New Mexico', 'Virgin Islands']

Health Care, Social Assistance
50
Empty state ['Alaska', 'New Mexico', 'Virgin Islands']

Leisure and Hospitality
53
Empty state []

Arts, Entertainment, Recreation
49
Empty state ['New Mexico', 'South Dakota', 'Puerto Rico', 'Virgin Islands']

Accommodation and Food Services
51
Empty state ['New Mexico', 'South Dakota']

Other Services
52
Empty state ['Virgin Islands']

Government
53
Empty state []

Federal Government
52
Empty state ['Virgin Islands']

State Government
52
Empty state ['District of Columbia']

Local Government
51
Empty state ['District of Columbia', 'Virgin Islands']

{'Alabama': {'number_of_missing': 0, 'missing_vars': []}, 'Alaska': {'number_of_missing': 3, 'missing_vars': ['Finance and Insurance', 'Educational Services', 'Health Care, Social Assistance']}, 'Arizona': {'number_of_missing': 1, 'missing_vars': ['Non-Durable Goods']}, 'Arkansas': {'number_of_missing': 0, 'missing_vars': []}, 'California': {'number_of_missing': 0, 'missing_vars': []}, 'Colorado': {'number_of_missing': 0, 'missing_vars': []}, 'Connecticut': {'number_of_missing': 0, 'missing_vars': []}, 'Delaware': {'number_of_missing': 3, 'missing_vars': ['Mining, Logging', 'Construction', 'Information']}, 'District of Columbia': {'number_of_missing': 7, 'missing_vars': ['Mining, Logging', 'Construction', 'Durable Goods', 'Non-Durable Goods', 'Management if Companies and Enterprises', 'State Government', 'Local Government']}, 'Florida': {'number_of_missing': 1, 'missing_vars': ['Mining, Logging']}, 'Georgia': {'number_of_missing': 0, 'missing_vars': []}, 'Hawaii': {'number_of_missing': 2, 'missing_vars': ['Mining, Logging', 'Construction']}, 'Idaho': {'number_of_missing': 0, 'missing_vars': []}, 'Illinois': {'number_of_missing': 0, 'missing_vars': []}, 'Indiana': {'number_of_missing': 0, 'missing_vars': []}, 'Iowa': {'number_of_missing': 0, 'missing_vars': []}, 'Kansas': {'number_of_missing': 0, 'missing_vars': []}, 'Kentucky': {'number_of_missing': 0, 'missing_vars': []}, 'Louisiana': {'number_of_missing': 1, 'missing_vars': ['Finance and Insurance']}, 'Maine': {'number_of_missing': 0, 'missing_vars': []}, 'Maryland': {'number_of_missing': 0, 'missing_vars': []}, 'Massachusetts': {'number_of_missing': 0, 'missing_vars': []}, 'Michigan': {'number_of_missing': 0, 'missing_vars': []}, 'Minnesota': {'number_of_missing': 0, 'missing_vars': []}, 'Mississippi': {'number_of_missing': 0, 'missing_vars': []}, 'Missouri': {'number_of_missing': 1, 'missing_vars': ['Finance and Insurance']}, 'Montana': {'number_of_missing': 3, 'missing_vars': ['Finance and Insurance', 'Management if Companies and Enterprises', 'Educational Services']}, 'Nebraska': {'number_of_missing': 0, 'missing_vars': []}, 'Nevada': {'number_of_missing': 0, 'missing_vars': []}, 'New Hampshire': {'number_of_missing': 0, 'missing_vars': []}, 'New Jersey': {'number_of_missing': 0, 'missing_vars': []}, 'New Mexico': {'number_of_missing': 11, 'missing_vars': ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Health Care, Social Assistance', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']}, 'New York': {'number_of_missing': 0, 'missing_vars': []}, 'North Carolina': {'number_of_missing': 0, 'missing_vars': []}, 'North Dakota': {'number_of_missing': 1, 'missing_vars': ['Management if Companies and Enterprises']}, 'Ohio': {'number_of_missing': 0, 'missing_vars': []}, 'Oklahoma': {'number_of_missing': 3, 'missing_vars': ['Durable Goods', 'Information', 'Finance and Insurance']}, 'Oregon': {'number_of_missing': 0, 'missing_vars': []}, 'Pennsylvania': {'number_of_missing': 0, 'missing_vars': []}, 'Rhode Island': {'number_of_missing': 2, 'missing_vars': ['Information', 'Real Estate, Rental, Leasing']}, 'South Carolina': {'number_of_missing': 0, 'missing_vars': []}, 'South Dakota': {'number_of_missing': 9, 'missing_vars': ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']}, 'Tennessee': {'number_of_missing': 0, 'missing_vars': []}, 'Texas': {'number_of_missing': 0, 'missing_vars': []}, 'Utah': {'number_of_missing': 0, 'missing_vars': []}, 'Vermont': {'number_of_missing': 1, 'missing_vars': ['Management if Companies and Enterprises']}, 'Virginia': {'number_of_missing': 0, 'missing_vars': []}, 'Washington': {'number_of_missing': 0, 'missing_vars': []}, 'West Virginia': {'number_of_missing': 1, 'missing_vars': ['Management if Companies and Enterprises']}, 'Wisconsin': {'number_of_missing': 0, 'missing_vars': []}, 'Wyoming': {'number_of_missing': 2, 'missing_vars': ['Finance and Insurance', 'Management if Companies and Enterprises']}, 'Puerto Rico': {'number_of_missing': 2, 'missing_vars': ['Management if Companies and Enterprises', 'Arts, Entertainment, Recreation']}, 'Virgin Islands': {'number_of_missing': 21, 'missing_vars': ['Mining, Logging', 'Mining, Logging, Construction', 'Construction', 'Manufacturing', 'Durable Goods', 'Non-Durable Goods', 'Wholesale Trade', 'Information', 'Financial Activities', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional and Business Services', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Health Care, Social Assistance', 'Arts, Entertainment, Recreation', 'Other Services', 'Federal Government', 'Local Government']}}
{'Total Nonfarm': {'number_of_missing': 0, 'missing_states': []}, 'Total Private': {'number_of_missing': 0, 'missing_states': []}, 'Goods Producing': {'number_of_missing': 0, 'missing_states': []}, 'Service-Providing': {'number_of_missing': 0, 'missing_states': []}, 'Private Service Providing': {'number_of_missing': 0, 'missing_states': []}, 'Mining, Logging': {'number_of_missing': 5, 'missing_states': ['Delaware', 'District of Columbia', 'Florida', 'Hawaii', 'Virgin Islands']}, 'Mining, Logging, Construction': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'Construction': {'number_of_missing': 4, 'missing_states': ['Delaware', 'District of Columbia', 'Hawaii', 'Virgin Islands']}, 'Manufacturing': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'Durable Goods': {'number_of_missing': 5, 'missing_states': ['District of Columbia', 'New Mexico', 'Oklahoma', 'South Dakota', 'Virgin Islands']}, 'Non-Durable Goods': {'number_of_missing': 5, 'missing_states': ['Arizona', 'District of Columbia', 'New Mexico', 'South Dakota', 'Virgin Islands']}, 'Trade, Transportation, Utilities': {'number_of_missing': 0, 'missing_states': []}, 'Wholesale Trade': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'Retail Trade': {'number_of_missing': 0, 'missing_states': []}, 'Transportation, Warehousing, Utilities': {'number_of_missing': 0, 'missing_states': []}, 'Information': {'number_of_missing': 4, 'missing_states': ['Delaware', 'Oklahoma', 'Rhode Island', 'Virgin Islands']}, 'Financial Activities': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'Finance and Insurance': {'number_of_missing': 9, 'missing_states': ['Alaska', 'Louisiana', 'Missouri', 'Montana', 'New Mexico', 'Oklahoma', 'South Dakota', 'Wyoming', 'Virgin Islands']}, 'Real Estate, Rental, Leasing': {'number_of_missing': 4, 'missing_states': ['New Mexico', 'Rhode Island', 'South Dakota', 'Virgin Islands']}, 'Professional and Business Services': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'Professional, Scientific, Technical Services': {'number_of_missing': 3, 'missing_states': ['New Mexico', 'South Dakota', 'Virgin Islands']}, 'Management if Companies and Enterprises': {'number_of_missing': 10, 'missing_states': ['District of Columbia', 'Montana', 'New Mexico', 'North Dakota', 'South Dakota', 'Vermont', 'West Virginia', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Ad-Sp-WM-R Services': {'number_of_missing': 3, 'missing_states': ['New Mexico', 'South Dakota', 'Virgin Islands']}, 'Education, Health Services': {'number_of_missing': 0, 'missing_states': []}, 'Educational Services': {'number_of_missing': 4, 'missing_states': ['Alaska', 'Montana', 'New Mexico', 'Virgin Islands']}, 'Health Care, Social Assistance': {'number_of_missing': 3, 'missing_states': ['Alaska', 'New Mexico', 'Virgin Islands']}, 'Leisure and Hospitality': {'number_of_missing': 0, 'missing_states': []}, 'Arts, Entertainment, Recreation': {'number_of_missing': 4, 'missing_states': ['New Mexico', 'South Dakota', 'Puerto Rico', 'Virgin Islands']}, 'Accommodation and Food Services': {'number_of_missing': 2, 'missing_states': ['New Mexico', 'South Dakota']}, 'Other Services': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'Government': {'number_of_missing': 0, 'missing_states': []}, 'Federal Government': {'number_of_missing': 1, 'missing_states': ['Virgin Islands']}, 'State Government': {'number_of_missing': 1, 'missing_states': ['District of Columbia']}, 'Local Government': {'number_of_missing': 2, 'missing_states': ['District of Columbia', 'Virgin Islands']}}

In [10]:
removed_state = ['Puerto Rico', 'Virgin Islands']
removed_var = [ 
         'Durable Goods',
         'Non-Durable Goods',
         'Finance and Insurance',
         'Real Estate, Rental, Leasing',
         'Professional, Scientific, Technical Services',
         'Management if Companies and Enterprises',
         'Ad-Sp-WM-R Services',
         'Arts, Entertainment, Recreation',
         'Accommodation and Food Services']

for state in removed_state:
    data = data[data['state'] != state]
for var in removed_var:
    data = data[data['industry'] != var]

In [11]:
missing_state_in_var, missing_var_in_state = filter_data(data)

Alabama
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Alaska
23
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Health Care, Social Assistance', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Arizona
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Arkansas
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

California
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Colorado
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Connecticut
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Delaware
22
Empty variables ['Mining, Logging', 'Construction', 'Durable Goods', 'Non-Durable Goods', 'Information', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

District of Columbia
21
Empty variables ['Mining, Logging', 'Construction', 'Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services', 'State Government', 'Local Government']

Florida
24
Empty variables ['Mining, Logging', 'Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Georgia
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Hawaii
23
Empty variables ['Mining, Logging', 'Construction', 'Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Idaho
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Illinois
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Indiana
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Iowa
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Kansas
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Kentucky
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Louisiana
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Maine
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Maryland
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Massachusetts
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Michigan
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Minnesota
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Mississippi
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Missouri
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Montana
24
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Nebraska
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Nevada
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

New Hampshire
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

New Jersey
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

New Mexico
23
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Educational Services', 'Health Care, Social Assistance', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

New York
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

North Carolina
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

North Dakota
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Ohio
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Oklahoma
24
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Information', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Oregon
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Pennsylvania
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Rhode Island
24
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Information', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

South Carolina
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

South Dakota
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Tennessee
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Texas
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Utah
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Vermont
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Virginia
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Washington
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

West Virginia
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Wisconsin
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Wyoming
25
Empty variables ['Durable Goods', 'Non-Durable Goods', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services']

Puerto Rico
0
Empty variables ['Total Nonfarm', 'Total Private', 'Goods Producing', 'Service-Providing', 'Private Service Providing', 'Mining, Logging', 'Mining, Logging, Construction', 'Construction', 'Manufacturing', 'Durable Goods', 'Non-Durable Goods', 'Trade, Transportation, Utilities', 'Wholesale Trade', 'Retail Trade', 'Transportation, Warehousing, Utilities', 'Information', 'Financial Activities', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional and Business Services', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Education, Health Services', 'Educational Services', 'Health Care, Social Assistance', 'Leisure and Hospitality', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services', 'Other Services', 'Government', 'Federal Government', 'State Government', 'Local Government']

Virgin Islands
0
Empty variables ['Total Nonfarm', 'Total Private', 'Goods Producing', 'Service-Providing', 'Private Service Providing', 'Mining, Logging', 'Mining, Logging, Construction', 'Construction', 'Manufacturing', 'Durable Goods', 'Non-Durable Goods', 'Trade, Transportation, Utilities', 'Wholesale Trade', 'Retail Trade', 'Transportation, Warehousing, Utilities', 'Information', 'Financial Activities', 'Finance and Insurance', 'Real Estate, Rental, Leasing', 'Professional and Business Services', 'Professional, Scientific, Technical Services', 'Management if Companies and Enterprises', 'Ad-Sp-WM-R Services', 'Education, Health Services', 'Educational Services', 'Health Care, Social Assistance', 'Leisure and Hospitality', 'Arts, Entertainment, Recreation', 'Accommodation and Food Services', 'Other Services', 'Government', 'Federal Government', 'State Government', 'Local Government']

Total Nonfarm
51
Empty state ['Puerto Rico', 'Virgin Islands']

Total Private
51
Empty state ['Puerto Rico', 'Virgin Islands']

Goods Producing
51
Empty state ['Puerto Rico', 'Virgin Islands']

Service-Providing
51
Empty state ['Puerto Rico', 'Virgin Islands']

Private Service Providing
51
Empty state ['Puerto Rico', 'Virgin Islands']

Mining, Logging
47
Empty state ['Delaware', 'District of Columbia', 'Florida', 'Hawaii', 'Puerto Rico', 'Virgin Islands']

Mining, Logging, Construction
51
Empty state ['Puerto Rico', 'Virgin Islands']

Construction
48
Empty state ['Delaware', 'District of Columbia', 'Hawaii', 'Puerto Rico', 'Virgin Islands']

Manufacturing
51
Empty state ['Puerto Rico', 'Virgin Islands']

Durable Goods
0
Empty state ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']

Non-Durable Goods
0

In [12]:
print (missing_state_in_var)
print (missing_var_in_state)

{'Total Nonfarm': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Total Private': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Goods Producing': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Service-Providing': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Private Service Providing': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Mining, Logging': {'number_of_missing': 6, 'missing_states': ['Delaware', 'District of Columbia', 'Florida', 'Hawaii', 'Puerto Rico', 'Virgin Islands']}, 'Mining, Logging, Construction': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Construction': {'number_of_missing': 5, 'missing_states': ['Delaware', 'District of Columbia', 'Hawaii', 'Puerto Rico', 'Virgin Islands']}, 'Manufacturing': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Durable Goods': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Non-Durable Goods': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Trade, Transportation, Utilities': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Wholesale Trade': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Retail Trade': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Transportation, Warehousing, Utilities': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Information': {'number_of_missing': 5, 'missing_states': ['Delaware', 'Oklahoma', 'Rhode Island', 'Puerto Rico', 'Virgin Islands']}, 'Financial Activities': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Finance and Insurance': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Real Estate, Rental, Leasing': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Professional and Business Services': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Professional, Scientific, Technical Services': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Management if Companies and Enterprises': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Ad-Sp-WM-R Services': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Education, Health Services': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Educational Services': {'number_of_missing': 5, 'missing_states': ['Alaska', 'Montana', 'New Mexico', 'Puerto Rico', 'Virgin Islands']}, 'Health Care, Social Assistance': {'number_of_missing': 4, 'missing_states': ['Alaska', 'New Mexico', 'Puerto Rico', 'Virgin Islands']}, 'Leisure and Hospitality': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Arts, Entertainment, Recreation': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Accommodation and Food Services': {'number_of_missing': 53, 'missing_states': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico', 'Virgin Islands']}, 'Other Services': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Government': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'Federal Government': {'number_of_missing': 2, 'missing_states': ['Puerto Rico', 'Virgin Islands']}, 'State Government': {'number_of_missing': 3, 'missing_states': ['District of Columbia', 'Puerto Rico', 'Virgin Islands']}, 'Local Government': {'number_of_missing': 3, 'missing_states': ['District of Columbia', 'Puerto Rico', 'Virgin Islands']}}

In [13]:
print(data.shape)
data.head()

(1258, 255)

,Series ID,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,...,May 2019,Jun 2019,Jul 2019,Aug 2019,Sep 2019,Oct 2019,Nov 2019,Dec 2019,state,industry
0,SMS01000000000000001,1921.1,1927.2,1929.9,1928.8,1930.2,1933.9,1935.9,1935.7,1939.7,...,2074.9,2078.4,2084.5,2087.5,2090.6,,,,Alabama,Total Nonfarm
1,SMS01000000500000001,1569.0,1574.4,1576.3,1574.0,1576.8,1580.2,1581.1,1581.2,1584.7,...,1685.2,1690.9,1696.3,1698.7,1701.9,,,,Alabama,Total Private
2,SMS01000000600000001,478.4,477.8,476.5,478.7,479.1,477.7,477.1,475.5,475.2,...,373.6,374.4,373.7,374.4,375.4,,,,Alabama,Goods Producing
3,SMS01000000700000001,1442.7,1449.4,1453.4,1450.1,1451.1,1456.2,1458.8,1460.2,1464.5,...,1701.3,1704.0,1710.8,1713.1,1715.2,,,,Alabama,Service-Providing
4,SMS01000000800000001,1090.6,1096.6,1099.8,1095.3,1097.7,1102.5,1104.0,1105.7,1109.5,...,1311.6,1316.5,1322.6,1324.3,1326.5,,,,Alabama,Private Service Providing

In [14]:
data.drop(['Series ID', 'Sep 2019', 'Oct 2019', 'Nov 2019', 'Dec 2019'], axis=1, inplace=True)

In [15]:
data.head()

,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,Oct 1999,...,Jan 2019,Feb 2019,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019,state,industry
0,1921.1,1927.2,1929.9,1928.8,1930.2,1933.9,1935.9,1935.7,1939.7,1939.7,...,2062.1,2065.8,2069.0,2070.0,2074.9,2078.4,2084.5,2087.5,Alabama,Total Nonfarm
1,1569.0,1574.4,1576.3,1574.0,1576.8,1580.2,1581.1,1581.2,1584.7,1585.5,...,1678.0,1680.6,1683.6,1682.9,1685.2,1690.9,1696.3,1698.7,Alabama,Total Private
2,478.4,477.8,476.5,478.7,479.1,477.7,477.1,475.5,475.2,474.9,...,371.4,372.3,374.2,373.9,373.6,374.4,373.7,374.4,Alabama,Goods Producing
3,1442.7,1449.4,1453.4,1450.1,1451.1,1456.2,1458.8,1460.2,1464.5,1464.8,...,1690.7,1693.5,1694.8,1696.1,1701.3,1704.0,1710.8,1713.1,Alabama,Service-Providing
4,1090.6,1096.6,1099.8,1095.3,1097.7,1102.5,1104.0,1105.7,1109.5,1110.6,...,1306.6,1308.3,1309.4,1309.0,1311.6,1316.5,1322.6,1324.3,Alabama,Private Service Providing

In [16]:
# Only keep the industry that appears in all states.
industries = data['industry'].unique()

In [17]:
len(industries)

25

In [18]:
states = data['state'].unique()

In [19]:
len(states)

51

In [20]:
industry_count = data.groupby(['industry'])['state'].count()

In [21]:
industry_count

industry
Construction                              48
Education, Health Services                51
Educational Services                      48
Federal Government                        51
Financial Activities                      51
Goods Producing                           51
Government                                51
Health Care, Social Assistance            49
Information                               48
Leisure and Hospitality                   51
Local Government                          50
Manufacturing                             51
Mining, Logging                           47
Mining, Logging, Construction             51
Other Services                            51
Private Service Providing                 51
Professional and Business Services        51
Retail Trade                              51
Service-Providing                         51
State Government                          50
Total Nonfarm                             51
Total Private                             51
Trade, Transportation, Utilities          51
Transportation, Warehousing, Utilities    51
Wholesale Trade                           51
Name: state, dtype: int64

In [22]:
keep_industries = industry_count[industry_count==51]

In [23]:
keep_industries = list(keep_industries.index)

In [24]:
del_industries = [ind for ind in industries if ind not in keep_industries]

In [25]:
del_industries

['Mining, Logging',
 'Construction',
 'Information',
 'Educational Services',
 'Health Care, Social Assistance',
 'State Government',
 'Local Government']

In [26]:
for ind in del_industries:
    data = data[data['industry']!=ind]

In [27]:
data = data.sort_values(['state', 'industry'])

In [28]:
data

,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,Oct 1999,...,Jan 2019,Feb 2019,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019,state,industry
23,176.3,176.8,176.9,177.2,177.0,178.1,177.6,177.2,178.1,179.1,...,246.2,246.3,247.0,247.7,248.1,249.3,252.0,252.0,Alabama,"Education, Health Services"
31,53.7,53.7,54.0,53.8,53.0,52.9,52.8,52.8,52.9,52.9,...,52.8,53.3,53.2,53.8,53.6,53.6,53.5,54.1,Alabama,Federal Government
16,96.8,97.4,97.5,97.2,97.5,97.6,97.4,97.5,97.7,98.2,...,97.3,96.7,97.2,97.9,97.7,98.4,98.3,97.6,Alabama,Financial Activities
2,478.4,477.8,476.5,478.7,479.1,477.7,477.1,475.5,475.2,474.9,...,371.4,372.3,374.2,373.9,373.6,374.4,373.7,374.4,Alabama,Goods Producing
30,352.1,352.8,353.6,354.8,353.4,353.7,354.8,354.5,355.0,354.2,...,384.1,385.2,385.4,387.1,389.7,387.5,388.2,388.8,Alabama,Government
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650,230.3,230.4,231.7,231.8,232.6,232.8,233.5,233.5,234.5,235.1,...,289.2,289.3,289.5,289.3,290.1,290.0,290.2,289.0,Wyoming,Total Nonfarm
1651,171.4,171.3,172.4,172.3,173.1,173.5,173.7,173.7,174.9,175.7,...,220.2,220.5,220.4,220.4,220.9,220.9,220.8,219.0,Wyoming,Total Private
1661,45.9,45.8,46.4,46.5,46.3,46.4,46.6,46.7,46.7,46.9,...,53.0,53.1,53.3,53.7,54.1,53.9,54.1,53.7,Wyoming,"Trade, Transportation, Utilities"
1664,11.1,11.0,11.3,11.4,11.4,11.6,11.5,11.4,11.4,11.3,...,14.8,15.0,15.1,15.4,15.3,15.2,15.3,15.1,Wyoming,"Transportation, Warehousing, Utilities"
1662,6.0,6.0,6.1,6.1,6.0,6.0,6.0,6.1,6.1,6.1,...,8.2,8.2,8.2,8.3,8.4,8.3,8.3,8.3,Wyoming,Wholesale Trade

In [40]:
data = data.iloc[:, -14:]

In [41]:
ts_df = data.iloc[:, :-2]

In [42]:
ts_df.astype(float)

,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019
23,245.3,246.2,246.7,246.9,246.2,246.3,247.0,247.7,248.1,249.3,252.0,252.0
31,53.0,53.0,53.3,53.1,52.8,53.3,53.2,53.8,53.6,53.6,53.5,54.1
16,96.4,97.7,97.0,96.9,97.3,96.7,97.2,97.9,97.7,98.4,98.3,97.6
2,368.2,369.2,369.0,372.5,371.4,372.3,374.2,373.9,373.6,374.4,373.7,374.4
30,387.0,385.5,386.2,385.2,384.1,385.2,385.4,387.1,389.7,387.5,388.2,388.8
...,...,...,...,...,...,...,...,...,...,...,...,...
1650,285.5,287.0,288.5,288.9,289.2,289.3,289.5,289.3,290.1,290.0,290.2,289.0
1651,216.7,217.9,219.3,219.9,220.2,220.5,220.4,220.4,220.9,220.9,220.8,219.0
1661,52.0,52.3,52.3,52.9,53.0,53.1,53.3,53.7,54.1,53.9,54.1,53.7
1664,14.5,14.4,14.6,14.8,14.8,15.0,15.1,15.4,15.3,15.2,15.3,15.1
1662,8.2,8.1,8.1,8.2,8.2,8.2,8.2,8.3,8.4,8.3,8.3,8.3

In [43]:
vals = ts_df.values

In [44]:
vals = vals.T

In [45]:
vals.shape

(12, 918)

In [46]:
vals

array([[245.3,  53. ,  96.4, ...,  52. ,  14.5,   8.2],
       [246.2,  53. ,  97.7, ...,  52.3,  14.4,   8.1],
       [246.7,  53.3,  97. , ...,  52.3,  14.6,   8.1],
       ...,
       [249.3,  53.6,  98.4, ...,  53.9,  15.2,   8.3],
       [252. ,  53.5,  98.3, ...,  54.1,  15.3,   8.3],
       [252. ,  54.1,  97.6, ...,  53.7,  15.1,   8.3]])

In [47]:
vals = vals.reshape(12, 51, 18)

In [48]:
vals

array([[[245.3,  53. ,  96.4, ..., 380.5,  75.5,  74.3],
        [ 50.5,  14.8,  11.7, ...,  64.4,  22.3,   6.5],
        [448.8,  55.5, 222.6, ..., 538.4, 112.8,  98.1],
        ...,
        [127.9,  23.4,  29.2, ..., 129.1,  27.1,  20.1],
        [457.1,  29. , 152.8, ..., 543. , 110.7, 127.7],
        [ 28.2,   7.5,  11.1, ...,  52. ,  14.5,   8.2]],

       [[246.2,  53. ,  97.7, ..., 380.9,  77.3,  74.2],
        [ 50.6,  14.9,  11.7, ...,  64.6,  22.4,   6.4],
        [451.7,  55.5, 223.1, ..., 536.9, 112.5,  98.6],
        ...,
        [128.3,  23.4,  29. , ..., 129.7,  27.7,  20.1],
        [456.8,  29.2, 153.5, ..., 537.9, 110.8, 126.8],
        [ 28.3,   7.6,  10.9, ...,  52.3,  14.4,   8.1]],

       [[246.7,  53.3,  97. , ..., 380.1,  77.6,  73.5],
        [ 50.7,  15. ,  11.5, ...,  64.7,  22.4,   6.4],
        [454.2,  55.9, 221.1, ..., 538.6, 112.8,  98.9],
        ...,
        [128.1,  23.5,  29.2, ..., 129.5,  28. ,  19.8],
        [457.6,  29.2, 153.4, ..., 540.9, 110.6, 127.6],
        [ 28.1,   7.7,  10.9, ...,  52.3,  14.6,   8.1]],

       ...,

       [[249.3,  53.6,  98.4, ..., 383.8,  78.5,  73.8],
        [ 50.6,  15.1,  12. , ...,  64.4,  22.3,   6.5],
        [463.5,  56.5, 221.8, ..., 544.2, 117.8, 100.2],
        ...,
        [131.2,  24.1,  29.5, ..., 131. ,  29.8,  20.5],
        [459.2,  29.1, 154.4, ..., 546.6, 112.3, 127.4],
        [ 27.6,   7.6,  11. , ...,  53.9,  15.2,   8.3]],

       [[252. ,  53.5,  98.3, ..., 384.5,  78.1,  73.5],
        [ 50.6,  15. ,  11.6, ...,  64.7,  22.2,   6.5],
        [466.5,  56.6, 222.2, ..., 544.9, 118.9, 100.6],
        ...,
        [130.7,  24.1,  29.7, ..., 131.3,  29.9,  20.4],
        [458.1,  29.1, 154.3, ..., 547.2, 112.9, 127.4],
        [ 27.8,   7.6,  10.9, ...,  54.1,  15.3,   8.3]],

       [[252. ,  54.1,  97.6, ..., 386.4,  78. ,  74. ],
        [ 50.2,  15.1,  11.6, ...,  64.5,  22.3,   6.6],
        [467.1,  56.9, 222.9, ..., 544.9, 119.8, 100.6],
        ...,
        [131.6,  24.3,  29.8, ..., 130.8,  29.7,  20.1],
        [458.2,  29.6, 153.8, ..., 547.9, 112.4, 128.1],
        [ 27.4,   7.7,  10.9, ...,  53.7,  15.1,   8.3]]])

In [49]:
vals[0, 0, :]

array([ 245.3,   53. ,   96.4,  368.2,  387. ,  205.5,  267.8,  100.4,
         96.7, 1290.5,  245. ,  230.7, 1677.5, 2045.7, 1658.7,  380.5,
         75.5,   74.3])

In [51]:
vals[0, 1, :]

array([ 50.5,  14.8,  11.7,  41.3,  80.4,  35.5,  12.7,  28.6,  11.1,
       206. ,  27.3,  35.6, 286.4, 327.7, 247.3,  64.4,  22.3,   6.5])

In [50]:
data.head(36)

,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019,state,industry
23,245.3,246.2,246.7,246.9,246.2,246.3,247.0,247.7,248.1,249.3,252.0,252.0,Alabama,"Education, Health Services"
31,53.0,53.0,53.3,53.1,52.8,53.3,53.2,53.8,53.6,53.6,53.5,54.1,Alabama,Federal Government
16,96.4,97.7,97.0,96.9,97.3,96.7,97.2,97.9,97.7,98.4,98.3,97.6,Alabama,Financial Activities
2,368.2,369.2,369.0,372.5,371.4,372.3,374.2,373.9,373.6,374.4,373.7,374.4,Alabama,Goods Producing
30,387.0,385.5,386.2,385.2,384.1,385.2,385.4,387.1,389.7,387.5,388.2,388.8,Alabama,Government
26,205.5,208.1,208.2,209.4,212.1,211.6,212.4,212.1,211.4,210.9,212.3,212.8,Alabama,Leisure and Hospitality
8,267.8,269.2,268.8,270.3,270.0,270.6,270.9,270.3,269.1,269.5,269.2,270.3,Alabama,Manufacturing
6,100.4,100.0,100.2,102.2,101.4,101.7,103.3,103.6,104.5,104.9,104.5,104.1,Alabama,"Mining, Logging, Construction"
29,96.7,97.3,97.7,98.2,98.9,98.9,98.3,98.4,98.5,99.1,99.9,99.6,Alabama,Other Services
4,1290.5,1295.5,1296.0,1299.9,1306.6,1308.3,1309.4,1309.0,1311.6,1316.5,1322.6,1324.3,Alabama,Private Service Providing
19,245.0,244.1,245.0,246.0,245.9,248.9,249.6,250.4,251.5,253.3,254.0,254.4,Alabama,Professional and Business Services
13,230.7,229.4,229.0,229.4,232.7,232.0,231.8,231.7,231.6,231.5,232.9,234.4,Alabama,Retail Trade
3,1677.5,1681.0,1682.2,1685.1,1690.7,1693.5,1694.8,1696.1,1701.3,1704.0,1710.8,1713.1,Alabama,Service-Providing
0,2045.7,2050.2,2051.2,2057.6,2062.1,2065.8,2069.0,2070.0,2074.9,2078.4,2084.5,2087.5,Alabama,Total Nonfarm
1,1658.7,1664.7,1665.0,1672.4,1678.0,1680.6,1683.6,1682.9,1685.2,1690.9,1696.3,1698.7,Alabama,Total Private
11,380.5,380.9,380.1,381.1,384.7,384.3,383.4,381.0,382.9,383.8,384.5,386.4,Alabama,"Trade, Transportation, Utilities"
14,75.5,77.3,77.6,77.8,77.8,77.5,76.6,75.9,77.5,78.5,78.1,78.0,Alabama,"Transportation, Warehousing, Utilities"
12,74.3,74.2,73.5,73.9,74.2,74.8,75.0,73.4,73.8,73.8,73.5,74.0,Alabama,Wholesale Trade
56,50.5,50.6,50.7,50.7,50.5,50.4,50.5,50.6,50.7,50.6,50.6,50.2,Alaska,"Education, Health Services"
62,14.8,14.9,15.0,14.9,14.9,14.8,14.8,14.9,15.2,15.1,15.0,15.1,Alaska,Federal Government
50,11.7,11.7,11.5,11.4,11.5,11.5,11.4,11.3,11.6,12.0,11.6,11.6,Alaska,Financial Activities
36,41.3,41.7,40.7,42.6,43.8,44.2,44.4,44.0,43.2,44.3,44.0,44.2,Alaska,Goods Producing
61,80.4,80.5,80.5,80.4,80.7,80.5,80.4,80.4,80.3,80.5,80.7,80.7,Alaska,Government
57,35.5,36.0,36.0,36.1,36.1,36.3,36.6,36.8,36.8,36.0,35.7,35.5,Alaska,Leisure and Hospitality
42,12.7,12.5,11.6,12.7,13.7,13.7,13.6,13.1,12.5,13.7,13.6,13.5,Alaska,Manufacturing
40,28.6,29.2,29.1,29.9,30.1,30.5,30.8,30.9,30.7,30.6,30.4,30.7,Alaska,"Mining, Logging, Construction"
60,11.1,10.9,10.7,10.9,10.9,10.8,10.9,11.1,11.2,11.2,10.7,10.8,Alaska,Other Services
38,206.0,206.6,205.9,206.1,206.0,205.8,206.7,207.6,208.8,207.7,206.8,205.8,Alaska,Private Service Providing
52,27.3,27.3,26.8,26.9,26.9,26.4,27.0,27.2,28.1,27.9,27.9,27.6,Alaska,Professional and Business Services
47,35.6,35.8,35.9,35.8,36.0,35.9,35.9,36.0,36.0,35.6,36.0,35.6,Alaska,Retail Trade
37,286.4,287.1,286.4,286.5,286.7,286.3,287.1,288.0,289.1,288.2,287.5,286.5,Alaska,Service-Providing
34,327.7,328.8,327.1,329.1,330.5,330.5,331.5,332.0,332.3,332.5,331.5,330.7,Alaska,Total Nonfarm
35,247.3,248.3,246.6,248.7,249.8,250.0,251.1,251.6,252.0,252.0,250.8,250.0,Alaska,Total Private
45,64.4,64.6,64.7,64.5,64.5,64.9,64.8,65.0,64.9,64.4,64.7,64.5,Alaska,"Trade, Transportation, Utilities"
48,22.3,22.4,22.4,22.2,22.0,22.5,22.3,22.4,22.4,22.3,22.2,22.3,Alaska,"Transportation, Warehousing, Utilities"
46,6.5,6.4,6.4,6.5,6.5,6.5,6.6,6.6,6.5,6.5,6.5,6.6,Alaska,Wholesale Trade

In [57]:
import json
with open('employment.json', 'w') as f:
    json.dump([[list(v1) for v1 in v] for v in vals], f)

In [59]:
keep_industries

['Education, Health Services',
 'Federal Government',
 'Financial Activities',
 'Goods Producing',
 'Government',
 'Leisure and Hospitality',
 'Manufacturing',
 'Mining, Logging, Construction',
 'Other Services',
 'Private Service Providing',
 'Professional and Business Services',
 'Retail Trade',
 'Service-Providing',
 'Total Nonfarm',
 'Total Private',
 'Trade, Transportation, Utilities',
 'Transportation, Warehousing, Utilities',
 'Wholesale Trade']